export const PERMISSIONS = {
  PLATFORM_CONFIG_MANAGE: "platform.config.manage",

  ORGANIZATION_READ: "organization.read",
  ORGANIZATION_MANAGE: "organization.manage",

  IDENTITY_USER_READ: "identity.user.read",
  IDENTITY_USER_MANAGE: "identity.user.manage",
  IDENTITY_ROLE_MANAGE: "identity.role.manage",

  PLANT_READ: "plant.read",
  PLANT_MANAGE: "plant.manage",

  MASTER_DATA_READ: "master-data.read",
  MASTER_DATA_MANAGE: "master-data.manage",

  SALES_ORDER_READ: "sales-order.read",
  SALES_ORDER_WRITE: "sales-order.write",

  WORK_ORDER_READ: "work-order.read",
  WORK_ORDER_WRITE: "work-order.write",
  WORK_ORDER_RELEASE: "work-order.release",

  PRODUCTION_READ: "production.read",
  PRODUCTION_EXECUTE: "production.execute",
  PRODUCTION_SUPERVISE: "production.supervise",
  PRODUCTION_HOLD: "production.hold",

  INVENTORY_READ: "inventory.read",
  INVENTORY_RECEIVE: "inventory.receive",
  INVENTORY_MOVE: "inventory.move",
  INVENTORY_RESERVE: "inventory.reserve",
  INVENTORY_ISSUE: "inventory.issue",
  INVENTORY_ADJUST: "inventory.adjust",

  QUALITY_READ: "quality.read",
  QUALITY_INSPECT: "quality.inspect",
  QUALITY_APPROVE: "quality.approve",
  QUALITY_NCR_CREATE: "quality.ncr.create",
  QUALITY_NCR_DISPOSITION: "quality.ncr.disposition",
  QUALITY_CAPA_MANAGE: "quality.capa.manage",

  AI_INSPECTION_READ: "ai-inspection.read",
  AI_INSPECTION_REQUEST: "ai-inspection.request",
  AI_INSPECTION_REVIEW: "ai-inspection.review",

  EQUIPMENT_READ: "equipment.read",
  EQUIPMENT_MANAGE: "equipment.manage",

  DOWNTIME_CLASSIFY: "downtime.classify",

  REPORT_READ: "report.read",
  AUDIT_READ: "audit.read",

  INTEGRATION_READ: "integration.read",
  INTEGRATION_MANAGE: "integration.manage",

  JOB_FAILED_READ: "job.failed.read",
  JOB_FAILED_REPLAY: "job.failed.replay",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const DEFAULT_ROLE_CODES = {
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  ORG_ADMIN: "ORG_ADMIN",
  PLANT_MANAGER: "PLANT_MANAGER",
  PLANNER: "PLANNER",
  SUPERVISOR: "SUPERVISOR",
  OPERATOR: "OPERATOR",
  QUALITY_INSPECTOR: "QUALITY_INSPECTOR",
  INVENTORY_OPERATOR: "INVENTORY_OPERATOR",
  MAINTENANCE_TECHNICIAN: "MAINTENANCE_TECHNICIAN",
  VIEWER: "VIEWER",
  INTEGRATION_SERVICE: "INTEGRATION_SERVICE",
} as const;

export type DefaultRoleCode =
  (typeof DEFAULT_ROLE_CODES)[keyof typeof DEFAULT_ROLE_CODES];

const P = PERMISSIONS;

const COMMON_READ = [
  P.PLANT_READ,
  P.MASTER_DATA_READ,
  P.SALES_ORDER_READ,
  P.WORK_ORDER_READ,
  P.PRODUCTION_READ,
  P.INVENTORY_READ,
  P.QUALITY_READ,
  P.AI_INSPECTION_READ,
  P.EQUIPMENT_READ,
  P.REPORT_READ,
] satisfies PermissionCode[];

export const ROLE_PERMISSIONS = {
  SYSTEM_ADMIN: [
    P.PLATFORM_CONFIG_MANAGE,
    P.ORGANIZATION_READ,
    P.IDENTITY_USER_READ,
    P.IDENTITY_USER_MANAGE,
    P.IDENTITY_ROLE_MANAGE,
    ...COMMON_READ,
    P.AUDIT_READ,
    P.INTEGRATION_READ,
    P.INTEGRATION_MANAGE,
    P.JOB_FAILED_READ,
    P.JOB_FAILED_REPLAY,
  ],

  ORG_ADMIN: [
    P.ORGANIZATION_READ,
    P.ORGANIZATION_MANAGE,
    P.IDENTITY_USER_READ,
    P.IDENTITY_USER_MANAGE,
    P.IDENTITY_ROLE_MANAGE,
    P.PLANT_READ,
    P.PLANT_MANAGE,
    ...COMMON_READ,
    P.AUDIT_READ,
    P.INTEGRATION_READ,
    P.INTEGRATION_MANAGE,
  ],

  PLANT_MANAGER: [
    ...COMMON_READ,
    P.ORGANIZATION_READ,
    P.IDENTITY_USER_READ,
    P.PLANT_MANAGE,
    P.WORK_ORDER_WRITE,
    P.WORK_ORDER_RELEASE,
    P.PRODUCTION_HOLD,
    P.INVENTORY_ADJUST,
    P.QUALITY_NCR_DISPOSITION,
    P.QUALITY_CAPA_MANAGE,
    P.AUDIT_READ,
    P.INTEGRATION_READ,
    P.JOB_FAILED_READ,
  ],

  PLANNER: [
    ...COMMON_READ,
    P.MASTER_DATA_MANAGE,
    P.SALES_ORDER_WRITE,
    P.WORK_ORDER_WRITE,
    P.WORK_ORDER_RELEASE,
    P.INVENTORY_RESERVE,
  ],

  SUPERVISOR: [
    ...COMMON_READ,
    P.PRODUCTION_EXECUTE,
    P.PRODUCTION_SUPERVISE,
    P.PRODUCTION_HOLD,
    P.INVENTORY_ISSUE,
    P.QUALITY_NCR_CREATE,
    P.DOWNTIME_CLASSIFY,
    P.AUDIT_READ,
  ],

  OPERATOR: [
    ...COMMON_READ,
    P.PRODUCTION_EXECUTE,
    P.INVENTORY_ISSUE,
    P.QUALITY_NCR_CREATE,
    P.DOWNTIME_CLASSIFY,
  ],

  QUALITY_INSPECTOR: [
    ...COMMON_READ,
    P.PRODUCTION_HOLD,
    P.QUALITY_INSPECT,
    P.QUALITY_APPROVE,
    P.QUALITY_NCR_CREATE,
    P.QUALITY_NCR_DISPOSITION,
    P.QUALITY_CAPA_MANAGE,
    P.AI_INSPECTION_REQUEST,
    P.AI_INSPECTION_REVIEW,
    P.AUDIT_READ,
  ],

  INVENTORY_OPERATOR: [
    ...COMMON_READ,
    P.INVENTORY_RECEIVE,
    P.INVENTORY_MOVE,
    P.INVENTORY_RESERVE,
    P.INVENTORY_ISSUE,
    P.INVENTORY_ADJUST,
  ],

  MAINTENANCE_TECHNICIAN: [
    P.PLANT_READ,
    P.MASTER_DATA_READ,
    P.WORK_ORDER_READ,
    P.PRODUCTION_READ,
    P.QUALITY_READ,
    P.EQUIPMENT_READ,
    P.EQUIPMENT_MANAGE,
    P.DOWNTIME_CLASSIFY,
    P.REPORT_READ,
    P.QUALITY_NCR_CREATE,
  ],

  VIEWER: [...COMMON_READ],

  INTEGRATION_SERVICE: [
    P.PLANT_READ,
    P.MASTER_DATA_READ,
    P.SALES_ORDER_READ,
    P.SALES_ORDER_WRITE,
    P.WORK_ORDER_READ,
    P.WORK_ORDER_WRITE,
    P.PRODUCTION_READ,
    P.PRODUCTION_EXECUTE,
    P.INVENTORY_READ,
    P.INVENTORY_RECEIVE,
    P.INVENTORY_MOVE,
    P.INVENTORY_RESERVE,
    P.INVENTORY_ISSUE,
    P.QUALITY_READ,
    P.QUALITY_INSPECT,
    P.QUALITY_NCR_CREATE,
    P.EQUIPMENT_READ,
    P.EQUIPMENT_MANAGE,
    P.DOWNTIME_CLASSIFY,
    P.REPORT_READ,
    P.INTEGRATION_READ,
    P.INTEGRATION_MANAGE,
    P.JOB_FAILED_READ,
    P.JOB_FAILED_REPLAY,
  ],
} satisfies Record<DefaultRoleCode, readonly PermissionCode[]>;
